"""add ai executions table

Revision ID: eed7a16521b1
Revises: 929fb5c946c5
Create Date: 2026-07-11 05:22:59.033755
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed7a16521b1'
down_revision: str | None = '929fb5c946c5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_executions',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('feature', sa.String(length=100), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response_preview', sa.String(length=500), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_executions_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_executions'))
    )
    with op.batch_alter_table('ai_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_executions_feature'), ['feature'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_executions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_executions_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_executions_feature'))

    op.drop_table('ai_executions')
    # ### end Alembic commands ###
