#!/usr/bin/env python3
"""Extract every Mermaid diagram from the docs into ``docs/diagrams/``.

Architecture Appendix B promises ``.mmd`` sources under ``docs/diagrams/``.
They were authored inline in the markdown instead, so the two drifted: the
directory never existed. Rather than hand-maintain a second copy — which would
drift again the first time a diagram changed — this derives the files from the
markdown, which stays the single source of truth.

Raster export is deliberately optional. GitHub, VS Code, and most markdown
viewers render ```mermaid fences natively, so PNG/SVG is no longer needed to
*read* a diagram; it matters for slides and printed docs. Rendering needs
``@mermaid-js/mermaid-cli``, which pulls a headless Chromium, so it runs only
with ``--render`` and only when ``mmdc`` is on PATH.

Usage:
    python scripts/export-diagrams.py            # write .mmd sources + index
    python scripts/export-diagrams.py --render   # also emit .svg (needs mmdc)
    python scripts/export-diagrams.py --check    # CI: fail if exports are stale
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUTPUT = DOCS / "diagrams"

# Files scanned for diagrams, in the order their sections should appear.
SOURCES = ["ARCHITECTURE.md", "PROJECT_ANALYSIS.md"]

_FENCE = re.compile(r"^```mermaid\s*$(.*?)^```\s*$", re.MULTILINE | re.DOTALL)
_HEADING = re.compile(r"^#{2,4}\s+(.*)$", re.MULTILINE)
_SLUG_STRIP = re.compile(r"[^a-z0-9]+")


@dataclass(frozen=True)
class Diagram:
    """One extracted diagram and where it came from."""

    source: str
    heading: str
    body: str

    @property
    def slug(self) -> str:
        base = _SLUG_STRIP.sub("-", self.heading.lower()).strip("-")
        return base or "diagram"


def _nearest_heading(text: str, position: int) -> str:
    """The closest heading above ``position`` — how a diagram gets its name."""
    best = "diagram"
    for match in _HEADING.finditer(text):
        if match.start() > position:
            break
        best = match.group(1).strip()
    return best


def extract(path: Path) -> list[Diagram]:
    text = path.read_text(encoding="utf-8")
    return [
        Diagram(
            source=path.name,
            heading=_nearest_heading(text, match.start()),
            body=match.group(1).strip() + "\n",
        )
        for match in _FENCE.finditer(text)
    ]


def collect() -> list[Diagram]:
    diagrams: list[Diagram] = []
    for name in SOURCES:
        path = DOCS / name
        if path.exists():
            diagrams.extend(extract(path))
    return diagrams


def planned_files(diagrams: list[Diagram]) -> dict[Path, str]:
    """Map output path -> contents, disambiguating repeated headings."""
    seen: dict[str, int] = {}
    files: dict[Path, str] = {}
    for diagram in diagrams:
        slug = diagram.slug
        count = seen.get(slug, 0)
        seen[slug] = count + 1
        name = slug if count == 0 else f"{slug}-{count + 1}"
        header = f"%% Generated from docs/{diagram.source} — edit that file, not this one.\n"
        files[OUTPUT / f"{name}.mmd"] = header + diagram.body
    files[OUTPUT / "README.md"] = _index(diagrams, files)
    return files


def _index(diagrams: list[Diagram], files: dict[Path, str]) -> str:
    lines = [
        "# Diagrams",
        "",
        "Generated by `scripts/export-diagrams.py` from the Mermaid blocks in",
        "`docs/ARCHITECTURE.md` and `docs/PROJECT_ANALYSIS.md`. **Do not edit these",
        "files** — change the source markdown and re-run the script.",
        "",
        "Markdown viewers render the originals inline, so these `.mmd` files exist",
        "for reuse elsewhere (slides, standalone rendering, diffing a diagram in",
        "isolation).",
        "",
        "| Diagram | Source |",
        "|---|---|",
    ]
    for path in files:
        if path.name == "README.md":
            continue
        source = next(
            (d.source for d in diagrams if d.slug == path.stem.rstrip("-0123456789")),
            "ARCHITECTURE.md",
        )
        lines.append(f"| [`{path.name}`](./{path.name}) | `docs/{source}` |")
    return "\n".join(lines) + "\n"


def render_svgs(paths: list[Path]) -> int:
    """Render .mmd -> .svg with mermaid-cli, if it is installed."""
    mmdc = shutil.which("mmdc")
    if mmdc is None:
        print(
            "mmdc not found — skipping SVG export.\n"
            "  Install with: npm install -g @mermaid-js/mermaid-cli",
            file=sys.stderr,
        )
        return 0
    rendered = 0
    for path in paths:
        target = path.with_suffix(".svg")
        result = subprocess.run(  # noqa: S603 - fixed binary, generated paths
            [mmdc, "-i", str(path), "-o", str(target), "-b", "transparent"],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            rendered += 1
        else:
            print(f"failed to render {path.name}: {result.stderr.strip()}", file=sys.stderr)
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--render", action="store_true", help="also export SVG (needs mmdc)")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed exports are stale",
    )
    args = parser.parse_args()

    diagrams = collect()
    if not diagrams:
        print("No mermaid diagrams found.", file=sys.stderr)
        return 1

    files = planned_files(diagrams)

    if args.check:
        stale = [
            path
            for path, content in files.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            print(
                "Diagram exports are stale; run scripts/export-diagrams.py:\n  "
                + "\n  ".join(str(p.relative_to(ROOT)) for p in stale),
                file=sys.stderr,
            )
            return 1
        print(f"{len(files) - 1} diagram(s) up to date.")
        return 0

    OUTPUT.mkdir(parents=True, exist_ok=True)
    for path, content in files.items():
        path.write_text(content, encoding="utf-8")
    mmd_files = [p for p in files if p.suffix == ".mmd"]
    print(f"Wrote {len(mmd_files)} diagram(s) to {OUTPUT.relative_to(ROOT)}/")

    if args.render:
        print(f"Rendered {render_svgs(mmd_files)} SVG(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
